# .github/workflows/gyrape-scan.yml

name: Gyrape Security Scan

# Trigger the workflow on push and pull request events to main or develop branches
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  gyrape-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Gyrape CLI
        run: |
          curl -sSL https://gyrape.io/install | bash

      - name: Run Gyrape Security Scan
        run: |
          gyrape .

      - name: Generate Gyrape Scan Report
        run: |
          gyrape report --scan-results ./gyrape-results.json --output ./report.html

      - name: Upload report artifact
        uses: actions/upload-artifact@v3
        with:
          name: gyrape-scan-report
          path: ./report.html
